config/routes.rb
Rails.application.routes.draw do

  # dailyco
  get 'admins/dailyco'

  # database
  resources :souvenirs
  resources :logins
  resources :userpositions do
    collection do 
      get 'regularly_delete'
    end
  end
  resources :users

  # space
  get 'space/index'

  # works
  get 'works/list'
  get 'works/:name', to: 'works#pages'

  # Slack
  post 'slack_notifications/submit'
  post 'slack_notifications/entered_page', format: 'json'
  post 'slack_notifications/daily_co_start', format: 'json'

  root 'space#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/userposition.rb
class Userposition < ApplicationRecord
end

app/controllers/userpositions_controller.rb
require "date"
class UserpositionsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_userposition, only: [:show, :edit, :update, :destroy]

  # GET /userpositions
  # GET /userpositions.json
  def index
    dst = []
    now = DateTime.now
    threshold = now - Rational(30, 24 * 60)
    Userposition.all.each do |userposition|
      if DateTime.parse(userposition[:created_at].to_s) > threshold
        dst.push(userposition)
      end
    end
    @userpositions = dst
  end

  # GET /userpositions/1
  # GET /userpositions/1.json
  def show
  end

  # GET /userpositions/new
  def new
    @userposition = Userposition.new
  end

  # GET /userpositions/1/edit
  def edit
  end

  # POST /userpositions
  # POST /userpositions.json
  def create
    @userposition = Userposition.new(userposition_params)
    # not save the same position.
    if same_position_exists()
      respond_to do |format|
        format.html { redirect_to @userposition, notice: 'this position is already exists.' }
        format.json { render json: { user: @userposition, status: 200, message: 'this position is already exists.' }, status: :ok }
      end
      return
    end

    if cookies[:user_id].nil?
      @userposition[:userid] = -1
      respond_to do |format|
        if @userposition.save
          format.html { redirect_to @userposition, notice: 'Userposition was successfully created.' }
          format.json { render json: { user: @userposition, status: 200, message: 'Created, no userid' }, status: :ok }
        else
          format.html { render :new }
          format.json { render json: { user: @userposition, status: 500, message: 'Internal server error : faliled to save' }, status: :internal_server_error }
        end
      end
    else
      @userposition[:userid] = cookies[:user_id]
      respond_to do |format|
        if @userposition.save
          format.html { redirect_to @userposition, notice: 'Userposition was successfully created.' }
          format.json { render json: { user: @userposition, status: 200, message: 'Created' }, status: :ok }
        else
          format.html { render :new }
          format.json { render json: { user: @userposition, status: 500, message: 'Internal server error : faliled to save' }, status: :internal_server_error }
        end
      end
    end
  end

  # PATCH/PUT /userpositions/1
  # PATCH/PUT /userpositions/1.json
  def update
    if @userposition.update(userposition_params)
      format.html { redirect_to @userposition, notice: 'Userposition was successfully updated.' }
      format.json { render json: { user: @userposition, status: 200, message: 'Updated' }, status: :ok }
    else
      format.html { render :edit }
      format.json { render json: { user: @userposition, status: 500, message: 'Internal server error : faliled to save' }, status: :internal_server_error }
    end
  end

  # DELETE /userpositions/1
  # DELETE /userpositions/1.json
  def destroy
    @userposition.destroy
    respond_to do |format|
      format.html { redirect_to userpositions_url, notice: 'Userposition was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  # 	2020-06-30 04:31:37 UTC
  def regularly_delete
    threshold = 15
    if Userposition.count < threshold
      render json: { status: 200, message: 'userposition table is too few (' + Userposition.count.to_s + ' records ) . failed to delete' }, status: :ok
      return
    end

    Userposition.first(Userposition.count - threshold).each do | userposition |
      now = DateTime.now
      created_time = DateTime.parse(userposition[:created_at].to_s)
      if now - Rational(10, 24*60) > created_time
        unless userposition.destroy
          render json: { status: 500, message: 'Internal server error : faliled to regularly delete' }, status: :internal_server_error 
        end
      end
    end

    render json: { status: 200, message: 'Completed regularly delete' }, status: :ok
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_userposition
      @userposition = Userposition.find_by(id: params[:id])
    end

    # Only allow a list of trusted parameters through.
    def userposition_params
      params.require(:userposition).permit(:userid, :x, :y, :z)
    end

    def same_position_exists
      !@userposition.nil? && Userposition.where(x: @userposition.x).where(y: @userposition.y).where(z: @userposition.z).exists? ? true : false
    end
end

app/helpers/userpositions_helper.rb
module UserpositionsHelper
end

app/views/userpositions/_form.html.erb
<%= form_with(model: userposition, local: true) do |form| %>
  <% if userposition.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(userposition.errors.count, "error") %> prohibited this userposition from being saved:</h2>

      <ul>
        <% userposition.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :userid %>
    <%= form.number_field :userid %>
  </div>

  <div class="field">
    <%= form.label :x %>
    <%= form.text_field :x %>
  </div>

  <div class="field">
    <%= form.label :y %>
    <%= form.text_field :y %>
  </div>

  <div class="field">
    <%= form.label :z %>
    <%= form.text_field :z %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/userpositions/edit.html.erb
<h1>Editing Userposition</h1>

<%= render 'form', userposition: @userposition %>

<%= link_to 'Show', @userposition %> |
<%= link_to 'Back', userpositions_path %>

app/views/userpositions/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Userpositions</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Userid</th>
      <th>X</th>
      <th>Y</th>
      <th>Z</th>
      <th>created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @userpositions.each do |userposition| %>
      <tr>
        <td><%= userposition.id %></td>
        <td><%= userposition.userid %></td>
        <td><%= userposition.x %></td>
        <td><%= userposition.y %></td>
        <td><%= userposition.z %></td>
        <td><%= userposition.created_at %></td>
        <td><%= link_to 'Show', userposition %></td>
        <td><%= link_to 'Edit', edit_userposition_path(userposition) %></td>
        <td><%= link_to 'Destroy', userposition, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Userposition', new_userposition_path %>

app/views/userpositions/new.html.erb
<h1>New Userposition</h1>
<h5>user idはcookieの値が自動で設定されます。   </h5>
<%= form_for @userposition, url: {action: "create"}, html: {class: "nifty_form"} do |f| %>
<% end %>

<%= render 'form', userposition: @userposition %>

<%= link_to 'Back', userpositions_path %>

app/views/userpositions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>X:</strong>
  <%= @userposition.x %>
</p>

<p>
  <strong>Y:</strong>
  <%= @userposition.y %>
</p>

<p>
  <strong>Z:</strong>
  <%= @userposition.z %>
</p>

<%= link_to 'Edit', edit_userposition_path(@userposition) %> |
<%= link_to 'Back', userpositions_path %>