config/routes.rb
Rails.application.routes.draw do

  # dailyco
  get 'admins/dailyco'

  # database
  resources :souvenirs
  resources :logins
  resources :userpositions do
    collection do 
      get 'regularly_delete'
    end
  end
  resources :users

  # space
  get 'space/index'

  # works
  get 'works/list'
  get 'works/:name', to: 'works#pages'

  # Slack
  post 'slack_notifications/submit'
  post 'slack_notifications/entered_page', format: 'json'
  post 'slack_notifications/daily_co_start', format: 'json'

  root 'space#index'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/souvenir.rb
class Souvenir < ApplicationRecord
end

app/controllers/souvenirs_controller.rb
class SouvenirsController < ApplicationController
  protect_from_forgery with: :null_session
  before_action :set_souvenir, only: [:show, :edit, :update, :destroy]

  # GET /souvenirs
  # GET /souvenirs.json
  def index
    @souvenirs = Souvenir.all
  end

  # GET /souvenirs/1
  # GET /souvenirs/1.json
  def show
  end

  # GET /souvenirs/new
  def new
    @souvenir = Souvenir.new
  end

  # GET /souvenirs/1/edit
  def edit
  end

  # POST /souvenirs
  # POST /souvenirs.json
  def create
    @souvenir = Souvenir.new(souvenir_params)

    respond_to do |format|
      if @souvenir.save
        format.html { redirect_to @souvenir, notice: 'Souvenir was successfully created.' }
        format.json { render json: { user: @souvenir, status: 200, description: 'Souvenir was successfully created.' }, status: :ok }
      else
        format.html { render :new }
        format.json { render json: { user: @souvenir, status: 500, description: 'Internal server error : faliled to save' }, status: :internal_server_error }
      end
    end
  end

  # PATCH/PUT /souvenirs/1
  # PATCH/PUT /souvenirs/1.json
  def update
    respond_to do |format|
      if @souvenir.update(souvenir_params)
        format.html { redirect_to @souvenir, notice: 'Souvenir was successfully updated.' }
        format.json { render json: { user: @souvenir, status: 200, description: 'Souvenir was successfully updated.' }, status: :ok }
      else
        format.html { render :edit }
        format.json { render json: { user: @souvenir, status: 500, description: 'Internal server error : faliled to save' }, status: :internal_server_error }
      end
    end
  end

  # DELETE /souvenirs/1
  # DELETE /souvenirs/1.json
  def destroy
    @souvenir.destroy
    respond_to do |format|
      format.html { redirect_to souvenirs_url, notice: 'Souvenir was successfully deleted.' }
      format.json { render json: { user: @souvenir, status: 200, description: 'Souvenir was successfully deleted.' }, status: :ok }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_souvenir
      @souvenir = Souvenir.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def souvenir_params
      params.require(:souvenir).permit(:impression, :works_1, :works_2, :works_3, :iris_11, :iris_12, :iris_13, :iris_14, :iris_21, :iris_22, :iris_23, :iris_24, :iris_31, :iris_32, :iris_33, :iris_34)
    end
end

app/helpers/souvenirs_helper.rb
module SouvenirsHelper
end

app/views/souvenirs/_form.html.erb
<%= form_with(model: souvenir, local: true) do |form| %>
  <% if souvenir.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(souvenir.errors.count, "error") %> prohibited this souvenir from being saved:</h2>

      <ul>
        <% souvenir.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :impression %>
    <%= form.text_area :impression %>
  </div>

  <div class="field">
    <%= form.label :works_1 %>
    <%= form.text_field :works_1 %>
  </div>

  <div class="field">
    <%= form.label :works_2 %>
    <%= form.text_field :works_2 %>
  </div>

  <div class="field">
    <%= form.label :works_3 %>
    <%= form.text_field :works_3 %>
  </div>

  <div class="field">
    <%= form.label :iris_11 %>
    <%= form.text_field :iris_11 %>
  </div>

  <div class="field">
    <%= form.label :iris_12 %>
    <%= form.text_field :iris_12 %>
  </div>

  <div class="field">
    <%= form.label :iris_13 %>
    <%= form.text_field :iris_13 %>
  </div>

  <div class="field">
    <%= form.label :iris_14 %>
    <%= form.text_field :iris_14 %>
  </div>

  <div class="field">
    <%= form.label :iris_21 %>
    <%= form.text_field :iris_21 %>
  </div>

  <div class="field">
    <%= form.label :iris_22 %>
    <%= form.text_field :iris_22 %>
  </div>

  <div class="field">
    <%= form.label :iris_23 %>
    <%= form.text_field :iris_23 %>
  </div>

  <div class="field">
    <%= form.label :iris_24 %>
    <%= form.text_field :iris_24 %>
  </div>

  <div class="field">
    <%= form.label :iris_31 %>
    <%= form.text_field :iris_31 %>
  </div>

  <div class="field">
    <%= form.label :iris_32 %>
    <%= form.text_field :iris_32 %>
  </div>

  <div class="field">
    <%= form.label :iris_33 %>
    <%= form.text_field :iris_33 %>
  </div>

  <div class="field">
    <%= form.label :iris_34 %>
    <%= form.text_field :iris_34 %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/souvenirs/edit.html.erb
<h1>Editing Souvenir</h1>

<%= render 'form', souvenir: @souvenir %>

<%= link_to 'Show', @souvenir %> |
<%= link_to 'Back', souvenirs_path %>

app/views/souvenirs/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Souvenirs</h1>

<table>
  <thead>
    <tr>
      <th>Impression</th>
      <th>Works 1</th>
      <th>Works 2</th>
      <th>Works 3</th>
      <th>Iris 11</th>
      <th>Iris 12</th>
      <th>Iris 13</th>
      <th>Iris 14</th>
      <th>Iris 21</th>
      <th>Iris 22</th>
      <th>Iris 23</th>
      <th>Iris 24</th>
      <th>Iris 31</th>
      <th>Iris 32</th>
      <th>Iris 33</th>
      <th>Iris 34</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @souvenirs.each do |souvenir| %>
      <tr>
        <td><%= souvenir.impression %></td>
        <td><%= souvenir.works_1 %></td>
        <td><%= souvenir.works_2 %></td>
        <td><%= souvenir.works_3 %></td>
        <td><%= souvenir.iris_11 %></td>
        <td><%= souvenir.iris_12 %></td>
        <td><%= souvenir.iris_13 %></td>
        <td><%= souvenir.iris_14 %></td>
        <td><%= souvenir.iris_21 %></td>
        <td><%= souvenir.iris_22 %></td>
        <td><%= souvenir.iris_23 %></td>
        <td><%= souvenir.iris_24 %></td>
        <td><%= souvenir.iris_31 %></td>
        <td><%= souvenir.iris_32 %></td>
        <td><%= souvenir.iris_33 %></td>
        <td><%= souvenir.iris_34 %></td>
        <td><%= link_to 'Show', souvenir %></td>
        <td><%= link_to 'Edit', edit_souvenir_path(souvenir) %></td>
        <td><%= link_to 'Destroy', souvenir, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Souvenir', new_souvenir_path %>

app/views/souvenirs/new.html.erb
<h1>New Souvenir</h1>

<%= render 'form', souvenir: @souvenir %>

<%= link_to 'Back', souvenirs_path %>

app/views/souvenirs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Impression:</strong>
  <%= @souvenir.impression %>
</p>

<p>
  <strong>Works 1:</strong>
  <%= @souvenir.works_1 %>
</p>

<p>
  <strong>Works 2:</strong>
  <%= @souvenir.works_2 %>
</p>

<p>
  <strong>Works 3:</strong>
  <%= @souvenir.works_3 %>
</p>

<p>
  <strong>Iris 11:</strong>
  <%= @souvenir.iris_11 %>
</p>

<p>
  <strong>Iris 12:</strong>
  <%= @souvenir.iris_12 %>
</p>

<p>
  <strong>Iris 13:</strong>
  <%= @souvenir.iris_13 %>
</p>

<p>
  <strong>Iris 14:</strong>
  <%= @souvenir.iris_14 %>
</p>

<p>
  <strong>Iris 21:</strong>
  <%= @souvenir.iris_21 %>
</p>

<p>
  <strong>Iris 22:</strong>
  <%= @souvenir.iris_22 %>
</p>

<p>
  <strong>Iris 23:</strong>
  <%= @souvenir.iris_23 %>
</p>

<p>
  <strong>Iris 24:</strong>
  <%= @souvenir.iris_24 %>
</p>

<p>
  <strong>Iris 31:</strong>
  <%= @souvenir.iris_31 %>
</p>

<p>
  <strong>Iris 32:</strong>
  <%= @souvenir.iris_32 %>
</p>

<p>
  <strong>Iris 33:</strong>
  <%= @souvenir.iris_33 %>
</p>

<p>
  <strong>Iris 34:</strong>
  <%= @souvenir.iris_34 %>
</p>

<%= link_to 'Edit', edit_souvenir_path(@souvenir) %> |
<%= link_to 'Back', souvenirs_path %>